### PR TITLE
MANIFEST.in: Add docs and test data

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/tableau/TabPy/issues/472

### CODE REVIEW

**Comment by 0golovatyi** [comment]
@jayvdb Could you clarify why and when those additional files needed in the package?

**Comment by jayvdb** [comment]
@0golovatyi , On https://github.com/tableau/TabPy/issues/472 you said you were approving it, but here you closed it without merging.

**Comment by 0golovatyi** [comment]
Sorry, my bad. Shouldn't have done it late night... Reopened and merged.

**Comment by jayvdb** [comment]
Minor note, not urgent, tag 2.3.2 hasnt been pushed to PyPI yet.

**Comment by jayvdb** [comment]
Still no 2.3.2 on PyPI @0golovatyi

**Comment by 0golovatyi** [comment]
@jayvdb There is no differences between 2.3.1 and 2.3.2 as test code is not added to the package.

**Pull request merged**
